services:
  mimir:
    image: 'grafana/mimir:2.12.0'
    volumes:
      - './config/mimir:/etc/mimir'
    entrypoint:
      - '/bin/mimir'
      - '-config.file=/etc/mimir/mimir.yaml'
    ports:
      - '9009:9009'

  grafana:
    image: 'grafana/grafana:10.4.2'
    volumes:
      - './config/grafana/config:/etc/grafana-config'
      - './config/grafana/datasources:/etc/grafana/provisioning/datasources'
      - './config/grafana/dashboards-provisioning:/etc/grafana/provisioning/dashboards'
      - './config/grafana/dashboards:/var/lib/grafana/dashboards'
    entrypoint:
      - '/usr/share/grafana/bin/grafana-server'
      - '--homepath=/usr/share/grafana'
      - '--config=/etc/grafana-config/grafana.ini'
    ports:
      - '3000:3000'

  loki:
    image: 'grafana/loki:3.0.0'
    command: '-config.file=/etc/loki/local-config.yaml'
    ports:
      - '3100:3100'

  tempo:
    image: 'grafana/tempo:2.4.1'
    volumes:
      - './config/tempo:/etc/tempo-config'
    command:
      - '-config.file=/etc/tempo-config/tempo.yaml'
      - '-config.expand-env=true'
    ports:
      - '3200:3200'

  alloy:
    image: 'grafana/alloy:v1.0.0'
    volumes:
      - './config/alloy:/etc/alloy'
    entrypoint:
      - '/bin/alloy'
      - 'run'
      - '--server.http.listen-addr=0.0.0.0:12345'
      - '--config.extra-args="-config.expand-env"'
      - '/etc/alloy/config.alloy'
    ports:
      - '12345:12345'
      - '8027:8027'
      - '4317:4317'
    depends_on:
      - 'mimir'
      - 'grafana'
      - 'loki'
      - 'tempo'
