receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins: '*'

processors:
  batch:
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 10s

exporters:
  prometheus:
    endpoint: '0.0.0.0:8889'
    enable_open_metrics: true
    const_labels:
      label1: value1
    resource_to_telemetry_conversion:
      enabled: true
    send_timestamps: true
  otlp/tempo:
    endpoint: 'http://tempo:4317'
    tls:
      insecure: true

  loki:
    endpoint: 'http://loki:3100/loki/api/v1/push'

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
